### ISSUE TITLE
Error when attempting installation

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-forseti#11]
When attempting to configure Forseti as follows:

```
module "forseti" {
	source = "github.com/terraform-google-modules/terraform-google-forseti"
	download_forseti = "true"
	gcs_location = "us-central1"
	cloud_sql_region = "us-central1"
	sendgrid_api_key = "<REDACTED>"
	notification_recipient_email = "jason@barefootcoders.com"
	gsuite_admin_email = "jason@barefootcoders.com"
	project_id = "${module.forseti-project.project_id}"
	credentials_file_path = "../credentials/terraform.json"
}
```

I receive an error message as follows:

```
Error: Error applying plan:

1 error(s) occurred:

* module.forseti.null_resource.execute_forseti: Error running command 'cd forseti-security; python install/gcp_installer.py --no-cloudshell --service-account-key-file ../credentials/terraform.json --gsuite-superadmin-email jason@barefootcoders.com --sendgrid-api-key <REDACTED> --cloudsql-region us-central1 --notification-recipient-email jason@barefootcoders.com --gcs-location us-central1': exit status 1. Output: Read gcloud info: Success
VPC Host Project barefoot-forseti

################################################################################
#  Installing Forseti Server                                                   #
################################################################################


+-------------------------------------------------------------------------------
|  Pre-installation checks
+-------------------------------------------------------------------------------

Dry run: False
Advanced mode: False
Read gcloud info: Success
Current gcloud version: 216.0.0
Gcloud alpha components: True
You are: terraform@root-project-216114.iam.gserviceaccount.com
Project id: barefoot-forseti
Organization id: 571656855759
Service account activated
Billing: Enabled

+-------------------------------------------------------------------------------
|  Configuring GSuite Admin Information
+-------------------------------------------------------------------------------

To read G Suite Groups and Users data, please provide a G Suite super admin email address. This step is optional.
See https://forsetisecurity.org/docs/latest/setup/install.html to know what will not work without G Suite integration.

Email: Traceback (most recent call last):
  File "install/gcp_installer.py", line 23, in <module>
    gcp_installer.run()
  File "/Users/jberlinsky/src/clients/BarefootCoders/google-infrastructure/forseti-security/install/gcp/gcp_installer.py", line 125, in run
    instructions = forseti_server.run_setup(final_setup=False)
  File "/Users/jberlinsky/src/clients/BarefootCoders/google-infrastructure/forseti-security/install/gcp/installer/forseti_installer.py", line 125, in run_setup
    self.preflight_checks()
  File "/Users/jberlinsky/src/clients/BarefootCoders/google-infrastructure/forseti-security/install/gcp/installer/forseti_server_installer.py", line 60, in preflight_checks
    self.get_email_settings()
  File "/Users/jberlinsky/src/clients/BarefootCoders/google-infrastructure/forseti-security/install/gcp/installer/forseti_server_installer.py", line 360, in get_email_settings
    constants.QUESTION_GSUITE_SUPERADMIN_EMAIL).strip()
EOFError: EOF when reading a line


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

At a very quick glance, it looks like [this line](https://github.com/GoogleCloudPlatform/forseti-security/blob/stable/install/gcp/installer/forseti_server_installer.py#L360) is trying to collect data from STDIN, which `null_resource.execute_forseti` is passing as a CLI flag. It looks like this changed on or about 8/23/2018, in [this commit](https://github.com/GoogleCloudPlatform/forseti-security/commit/7af8d0f64d9a5ba98d73792555bb5b8f28fd00c4).

**Temporary Resolution:** If I go into the cloned `forseti-security/` repository and check out the prior commit, https://github.com/GoogleCloudPlatform/forseti-security/commit/87e42da7a9f217a99583858e89999785fef15f75, I'm able to proceed with deploying Forseti.

**Suggested Fix:** This seems to be an issue with Forseti itself, but it also seems unnecessarily restrictive to limit Forseti checkouts to just branch names. Perhaps an appropriate first step here would be allowing all git refs (including SHAs and named branches) to be used in the `forseti_repo_branch` variable. From there, some GH Issues should probably be filed with the Forseti project.

**Comment by johnrevans6** [comment]
Yeah, this looks Forseti related. What branch did you check this out from? I'm working on some improvements to both Forseti and the Forseti module, but no eta on that.

**Comment by lbastet** [comment]
Hi! I had make some changes if you want you can check and use it: 
https://github.com/lbastet/terraform-google-forseti/tree/changes
I have asked for a pull request

**Comment by adrienthebo** [comment]
This module has been rewritten from the ground up to drop the Deployment Manager dependency and we're now targeting v2.11. Because so much of the module has been changed and we're not calling into the code in question I'm going to venture that this issue has been resolved. If this is still an issue please comment on this pull request and I can reopen it to resume this conversation.
